### ISSUE TITLE
backend: routes, models, controllers, db folder

### ISSUE THREAD

**Issue by himanshujaidka** [DevMan-open-source/dailymint#6]
initialize the mentioned empty folders

**Comment by khushi-purwar** [comment]
> initialize the mentioned empty folders

Can i work on this issue?

**Comment by himanshujaidka** [comment]
> > initialize the mentioned empty folders
> 
> Can i work on this issue?

yes, but before that you have to setup the node server

**Comment by khushi-purwar** [comment]
> > > initialize the mentioned empty folders
> > 
> > 
> > Can i work on this issue?
> 
> yes, but before that you have to setup the node server

Yed, i will do that

**Comment by himanshujaidka** [comment]
okay, then go ahead :)

**Comment by himanshujaidka** [comment]
@khushi-purwar any updates?

**Comment by khushi-purwar** [comment]
> @khushi-purwar any updates?

yes I completed my work, but unable to push @himanshujaidka

**Comment by himanshujaidka** [comment]
> > @khushi-purwar any updates?
> 
> yes I completed my work, but unable to create PR @himanshujaidka
> 
> <img alt="2021-07-20" width="960" src="https://user-images.githubusercontent.com/52875298/126266698-df826182-3874-4b60-bf86-c8df60a2030b.png">
> 
> I am getting this

have you refreshed it?

**Comment by khushi-purwar** [comment]
> > > @khushi-purwar any updates?
> > 
> > 
> > yes I completed my work, but unable to create PR @himanshujaidka
> > <img alt="2021-07-20" width="960" src="https://user-images.githubusercontent.com/52875298/126266698-df826182-3874-4b60-bf86-c8df60a2030b.png">
> > I am getting this
> 
> have you refreshed it? and you need to add something inside files

Ok. I will add content inside files

**Comment by khushi-purwar** [comment]
I have added the content in the files, but still PR is not Creating.


<img width="960" alt="2021-07-20 (1)" src="https://user-images.githubusercontent.com/52875298/126296461-773280aa-ab68-411b-9bdc-5e276d29d6f7.png">
